### ISSUE TITLE
Version 0.2.2 Breaks Rake db: methods

### ISSUE THREAD

**Issue by DevGW** [mehdi-farsi/activerecord-search#2]
removing gem from Gemfile then running rake, then reinstalling gem seems to be a workaround.

OS: Max OS X Sierra
Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
Rails: Version: 5.0.0.1
Gems Installed:
```
Gems included by the bundle:
  * actioncable (5.0.0.1)
  * actionmailer (5.0.0.1)
  * actionpack (5.0.0.1)
  * actionview (5.0.0.1)
  * active_model_serializers (0.10.2)
  * activejob (5.0.0.1)
  * activemodel (5.0.0.1)
  * activerecord (5.0.0.1)
  * activerecord-search (0.2.2)
  * activesupport (5.0.0.1)
  * arel (7.1.4)
  * builder (3.2.2)
  * bundler (1.13.6)
  * byebug (9.0.6)
  * coffee-rails (4.2.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * concurrent-ruby (1.0.2)
  * debug_inspector (0.0.2)
  * erubis (2.7.0)
  * execjs (2.7.0)
  * ffi (1.9.14)
  * font-awesome-rails (4.7.0.0)
  * globalid (0.3.7)
  * i18n (0.7.0)
  * jbuilder (2.6.0)
  * jquery-rails (4.2.1)
  * jsonapi (0.1.1.beta6)
  * jsonapi-parser (0.1.1.beta3)
  * jsonapi-renderer (0.1.1.beta1)
  * listen (3.0.8)
  * loofah (2.0.3)
  * mail (2.6.4)
  * method_source (0.8.2)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mini_portile2 (2.1.0)
  * minitest (5.9.1)
  * multi_json (1.12.1)
  * mysql2 (0.4.5)
  * nio4r (1.2.1)
  * nokogiri (1.6.8.1)
  * puma (3.6.0)
  * rack (2.0.1)
  * rack-test (0.6.3)
  * rails (5.0.0.1)
  * rails-dom-testing (2.0.1)
  * rails-html-sanitizer (1.0.3)
  * railties (5.0.0.1)
  * rake (11.3.0)
  * rb-fsevent (0.9.8)
  * rb-inotify (0.9.7)
  * sass (3.4.22)
  * sass-rails (5.0.6)
  * spring (2.0.0)
  * spring-watcher-listen (2.0.1)
  * sprockets (3.7.0)
  * sprockets-rails (3.2.0)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (2.0.5)
  * turbolinks (5.0.1)
  * turbolinks-source (5.0.0)
  * tzinfo (1.2.2)
  * uglifier (3.0.3)
  * web-console (3.4.0)
  * websocket-driver (0.6.4)
  * websocket-extensions (0.1.2)
  * will_paginate (3.1.5)

```
Output of any rake db:(command):

```
CrypT3ch:giuat asdf$ rake db:migrate VERSION=20161110152634 --trace


** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
rake aborted!
SyntaxError: (eval):4: syntax error, unexpected '/', expecting ';' or '\n'
...      def search_active_record/internal_metadata(words, opti...
...                               ^
(eval):58: syntax error, unexpected keyword_end, expecting end-of-input
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-search-0.2.2/lib/activerecord/base.rb:16:in `class_eval'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-search-0.2.2/lib/activerecord/base.rb:16:in `inherited'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/internal_metadata.rb:7:in `<module:ActiveRecord>'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/internal_metadata.rb:4:in `<top (required)>'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/sdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1014:in `initialize_internal_metadata_table'
/Users/sadf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1109:in `initialize'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1005:in `new'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1005:in `up'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:989:in `migrate'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/Users/asdf/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/asdf/.rbenv/versions/2.3.1/bin/rake:23:in `load'
/Users/asdf/.rbenv/versions/2.3.1/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by sapereau83** [comment]
Thanks for your feedback !
I'm on it ;) I come back to you soon !

**Comment by DevGW** [comment]
Awesome!  ... and great work I love the simplicity of this gem and using it!

**Comment by DevGW** [comment]
any update on this?
